# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-23 02:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('birthday', models.CharField(max_length=20)),
                ('age', models.DecimalField(decimal_places=0, max_digits=3)),
            ],
        ),
    ]
